usb_cam:
  ros__parameters:
    video_device: "/dev/video0"
    image_width: 640
    image_height: 480
    pixel_format: "yuyv"
    camera_frame_id: "camera_frame"
    io_method: "mmap"
    framerate: 30.0
